# Production secrets (should be managed via secret manager)
# These are placeholders - actual values should be injected via environment
secrets:
  database_password: ${DATABASE_PASSWORD}
  redis_password: ${REDIS_PASSWORD}
  ibkr_password: ${IBKR_PASSWORD}
  
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600