server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      # Extract container name from filename
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id>[a-z0-9]+)/.*'
      
      # Parse JSON logs from Docker
      - json:
          expressions:
            stream: stream
            log: log
            time: time
      
      # Extract container name from Docker labels
      - docker: {}
      
      # Add labels
      - labels:
          container_name:
          container_id:
      
      # Filter specific services
      - match:
          selector: '{container_name=~"trade_.*"}'
          stages:
            - regex:
                expression: '(?P<level>INFO|WARN|ERROR|DEBUG)'
            - labels:
                level:

  # System logs (optional)
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog