version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: trade_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: trade_db
      POSTGRES_USER: trade_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-trade_pass}
    ports:
      - "5432:5432"
    volumes:
      - ../../volumes/postgresql:/var/lib/postgresql/data
      - ../../configs/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - trade_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trade_user -d trade_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache (optional, for future use)
  redis:
    image: redis:7-alpine
    container_name: trade_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ../../volumes/redis:/data
      - ../../configs/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - trade_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ../../../trade_dashboard
      dockerfile: Dockerfile
    container_name: trade_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://trade_user:${DB_PASSWORD:-trade_pass}@db:5432/trade_db
      REDIS_URL: redis://redis:6379
      IB_HOST: ${IB_HOST:-host.docker.internal}
      IB_PORT: ${IB_PORT:-7497}
      IB_CLIENT_ID: ${IB_CLIENT_ID:-1}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DEBUG: ${DEBUG:-false}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trade_network
    volumes:
      - ../../../trade_dashboard/trading.db:/app/trading.db  # For SQLite compatibility
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For accessing IBKR on host

  # Frontend
  frontend:
    build:
      context: ../../../trade_frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
        VITE_WS_URL: ${VITE_WS_URL:-ws://localhost:8000}
    container_name: trade_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
      VITE_WS_URL: ${VITE_WS_URL:-ws://localhost:8000}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - trade_network

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ../proxy/nginx
      dockerfile: Dockerfile
    container_name: trade_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../proxy/nginx/ssl:/etc/nginx/ssl:ro  # SSL certificates if needed
    depends_on:
      - backend
      - frontend
    networks:
      - trade_network

  # ML Model Serving (Optional - comment out if not using ML features)
  # ml-serving:
  #   build:
  #     context: ../ml-serving
  #     dockerfile: Dockerfile
  #   container_name: trade_ml_serving
  #   restart: unless-stopped
  #   environment:
  #     MODEL_NAME: ${ML_MODEL_NAME:-trade_model}
  #     MODEL_BASE_PATH: ${ML_MODEL_BASE_PATH:-/models}
  #   ports:
  #     - "${ML_REST_PORT:-8501}:8501"  # REST API
  #     - "${ML_GRPC_PORT:-8500}:8500"  # gRPC API
  #   volumes:
  #     - ../../volumes/models:/models:ro
  #   networks:
  #     - trade_network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8501/v1/models/${ML_MODEL_NAME:-trade_model}"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

networks:
  trade_network:
    driver: bridge