version: '3.8'

# Docker Registry 설정
# 위치: /opt/docker-registry/docker-compose.yml

services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # 기본 설정
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      
      # SSL 설정 (Let's Encrypt 인증서 사용)
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/key.pem
      
      # 인증 설정
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      
      # 기타 설정
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_LOG_LEVEL: info
      
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth:ro
      - ./certs:/certs:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "https://localhost:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Registry Web UI (선택사항)
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: unless-stopped
    ports:
      - "5001:80"
    environment:
      - REGISTRY_TITLE=Trade System Docker Registry
      - REGISTRY_URL=https://registry:5000
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true
      - NGINX_PROXY_PASS_URL=https://registry:5000
    depends_on:
      - registry

  # Registry 가비지 컬렉션을 위한 크론잡 (선택사항)
  registry-gc:
    image: registry:2
    container_name: registry-gc
    restart: "no"
    entrypoint: |
      sh -c 'while true; do
        echo "Running garbage collection..."
        /bin/registry garbage-collect /etc/docker/registry/config.yml
        echo "Garbage collection completed. Sleeping for 24 hours..."
        sleep 86400
      done'
    volumes:
      - ./data:/var/lib/registry
    profiles:
      - maintenance