version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: trade-postgres
    environment:
      POSTGRES_DB: trade_master
      POSTGRES_USER: trade_user
      POSTGRES_PASSWORD: trade_pass_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script/sql:/docker-entrypoint-initdb.d
    networks:
      - trade-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trade_user -d trade_master"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching and messaging
  redis:
    image: redis:7-alpine
    container_name: trade-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trade-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trade-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@trade.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - trade-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  # IB Gateway
  ib-gateway:
    image: ghcr.io/gnzsnz/ib-gateway:latest
    container_name: trade-ib-gateway
    environment:
      TWS_USERID: ${IB_USER:-demo}
      TWS_PASSWORD: ${IB_PASSWORD:-demo123}
      TWS_TRADINGMODE: paper  # paper or live
      TWS_ACCEPTINCOMINGCONNECTIONACTION: accept
      TWS_LOGINTIMEOUT: 60
      TWOFA_TIMEOUT_ACTION: restart
    ports:
      - "4001:4001"  # TWS API port (live)
      - "4002:4002"  # TWS API port (paper)
      - "5900:5900"  # VNC port for GUI access
    volumes:
      - ib_gateway_data:/opt/ibc
      - ./logs:/opt/ibc/logs
    networks:
      - trade-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :4002 | grep LISTEN || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # IB Gateway needs time to start up

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  ib_gateway_data:
    driver: local

networks:
  trade-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16