version: '3.8'

services:
  batch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trade_batch
    environment:
      - DATABASE_URL=postgresql://freeksj:freeksj@db:5432/trade
      - REDIS_URL=redis://redis:6379
      - IBKR_HOST=host.docker.internal
      - IBKR_PORT=4002
      - IBKR_CLIENT_ID=2
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - TZ=Asia/Seoul
    ports:
      - "8082:8082"
    volumes:
      - batch-logs:/app/logs
      - ./src:/app/src:ro
    restart: unless-stopped

volumes:
  batch-logs: