version: '3.8'

services:
  ib-gateway:
    image: ghcr.io/gnzsnz/ib-gateway:latest
    container_name: trade-ib-gateway-v2
    restart: unless-stopped
    environment:
      TWS_USERID: ${TWS_USERID:-}
      TWS_PASSWORD: ${TWS_PASSWORD:-}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_ACCEPT_INCOMING: 'accept'
      VNC_PASSWORD: 'vnc123'
      TZ: 'Asia/Seoul'
    ports:
      - "4001:4001"  # Live trading
      - "4002:4002"  # Paper trading
      - "5900:5900"  # VNC
    volumes:
      - ib-gateway-config:/config
      - ib-gateway-logs:/var/log
    networks:
      - trade-network

volumes:
  ib-gateway-config:
  ib-gateway-logs:

networks:
  trade-network:
    external: true