spring:
  application:
    name: trade_batch
  main:
    banner-mode: false
  profiles:
    active: dev
  task:
    scheduling:
      timezone: UTC
  batch:
    job:
      enabled: false
      names:
    jdbc:
      initialize-schema: always
  jackson:
    time-zone: Asia/Seoul
  ### DataBase ###
#  datasource:
#    url: jdbc:sqlite:C:/Workspace/workspace_python/ibkr/trade_engine/src/infra/sqlite/trade.sqlite
#    driver-class-name: org.sqlite.JDBC
#    username: null
#    password: null
#  jpa:
#    database-platform: org.hibernate.community.dialect.SQLiteDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

#  datasource:
#    url: jdbc:duckdb:C:/Workspace/trade_engine/infra/duckdb/batch.duckdb
#    driver-class-name: org.duckdb.DuckDBDriver
#    username:
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.DuckDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/trade_db
    driver-class-name: org.postgresql.Driver
    username: freeksj
    password: Lsld1501!
    trade:
      url: jdbc:postgresql://localhost:5432/trade_db
      driver-class-name: org.postgresql.Driver
      username: freeksj
      password: Lsld1501!
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
    data-us:
      url: jdbc:postgresql://localhost:5432/trade_db
      driver-class-name: org.postgresql.Driver
      username: freeksj
      password: Lsld1501!
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
    data-cn:
      url: jdbc:postgresql://localhost:5432/trade_db
      driver-class-name: org.postgresql.Driver
      username: freeksj
      password: Lsld1501!
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
    data-eu:
      url: jdbc:postgresql://localhost:5432/trade_db
      driver-class-name: org.postgresql.Driver
      username: freeksj
      password: Lsld1501!
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

logging:
  level:
    org.springframework.batch: INFO
    com.trade.batch: DEBUG
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger - %msg%n'

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true

ibkr:
  api:
    host: ${IB_HOST:localhost}
    port: ${IB_PORT:4001}
    clientId: ${IB_CLIENT_ID_BATCH:30}
    username: ${IB_USERNAME:}
    password: ${IB_PASSWORD:}
