spring:
  application:
    name: trade_batch
  main:
    banner-mode: false
  profiles:
    active: dev
  task:
    scheduling:
      timezone: UTC
  batch:
    job:
      enabled: false
      names:
    jdbc:
      initialize-schema: always
  jackson:
    time-zone: Asia/Seoul
  ### DataBase ###

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:trade_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:freeksj}
    password: ${DB_PASSWORD:Lsld1501!}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

logging:
  level:
    org.springframework.batch: INFO
    com.trade.batch: DEBUG
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger - %msg%n'

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true

ibkr:
  api:
    host: ${IBKR_HOST:localhost}
    port: ${IBKR_PORT:4002}
    clientId: ${IBKR_CLIENT_ID:1}
    username: ${IBKR_USERNAME:}
    password: ${IBKR_PASSWORD:}
