# Development secrets (not for production)
secrets:
  database_password: Lsld1501!
  redis_password: ""
  ibkr_password: Lsld1501!
  
# JWT for development
jwt:
  secret: dev-secret-key-change-in-production
  expiration: 3600